[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
size = 12.0

[window]
decorations = "Buttonless"
option_as_alt = "Both"

[window.padding]
x = 10
y = 10
